### ISSUE TITLE
Script error on Lanch

### ISSUE THREAD

**Issue by nicobowen** [euloggeradmin/LootNanny#2]
Hello,

I had the program working for around 72 hours.

On starting the program I now get this error

"Traceback (most recent call last):
  File "LootNanny.py", line 440, in <module>
  File "LootNanny.py", line 428, in create_ui
  File "LootNanny.py", line 47, in __init__
  File "modules\combat.py", line 292, in __init__
  File "modules\combat.py", line 442, in load_runs
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
"

**Comment by Beryn-ivo** [comment]
I get the same error now. It worked for about a week then I get this when I try to launch it.
